name: 'update schedule'

on:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
      - dev
jobs:
  push:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        operating-system: ['ubuntu-20.04']
    steps:
      - uses: actions/checkout@v3 # Checking out the repo
      - name: Run with setup-python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          update-environment: false
          cache: 'pipenv'

      - name: Install Selenium
        run: |
          sudo pip3 install selenium
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Download chrome driver
        uses: nanasess/setup-chromedriver@master
      - name: Launch chrome driver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Set final file name
        id: set_final_file_name
        run: |
          echo "::set-output name=final_file::$(python -c 'import config; print(config.final_file)')"

      - name: Install pipenv
        run: pip3 install --user pipenv
      - name: Install dependecies
        run: pipenv --python python3 && pipenv install
      - name: Build
        run: pipenv run build
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff
          if [[ -f ${{ steps.set_final_file_name.outputs.final_file }} ]]; then
            git add ${{ steps.set_final_file_name.outputs.final_file }}
          fi
          if [[ -f result.log ]]; then
            git add result.log
          fi
          if [[ `git status --porcelain` ]]; then
            git commit -m "Github Action Auto Updated"
            git push
          fi
